### ISSUE TITLE
Feature Request: Live Wallpaper version for android based on the web port.

### ISSUE THREAD

**Issue by lexterror** [sandydoo/flux#10]
Hi,

From what I know I think its fairly simple to make an Android live wallpaper from the web version of your app. 

Thank you!

**Comment by lexterror** [comment]
I created this a few months based on a script that is no longer available. And it works really nicely. I never had the time to set it as a live wallpaper.

https://github.com/lexterror/fire3dandroid

**Comment by lexterror** [comment]
Also: Im using your screensaver as a live wallpaper on Windows thanks to this:

https://github.com/teknixstuff/screenpaper

**Comment by sandydoo** [comment]
Thanks, @lexterror!

This sounds like a feature that could live in a separate repo. I don't own an Android device, so it would be a burden for me to review and accept any PRs for more platforms.

If you decide to build something like this, let me know and I'll add a link to your project in the README 👍
