### ISSUE TITLE
Support for frontend framework integration

### ISSUE THREAD

**Issue by donny-son** [sandydoo/flux#9]
Fascinating project..Are there any plans on providing the background as a component that works with frontend libraries/frameworks such as React/Vue?

**Comment by sandydoo** [comment]
Thanks, @donny-son! No, I don't plan on adding any integrations. This is more of a standalone art project really.

That being said, I've purposefully written Flux as a cross-platform library to make it possible to integrate with other languages/frameworks. [flux-wasm](https://github.com/sandydoo/flux/tree/main/flux-wasm), [flux-desktop](https://github.com/sandydoo/flux/tree/main/flux-desktop), and [flux-screensavers](https://github.com/sandydoo/flux-screensavers) are mostly code-glue around that library.
